### ISSUE TITLE
get-post hard test cases.

### ISSUE THREAD

**Issue by Jaardy** [accuser/week-6-assignments#2]
It's testing for a redirect and a 302 response.  I was unclear from the directions that this was needed.

**Comment by accuser** [comment]
I consider tests as part of the documentation, and this *is* a hard test case. `d1/2-medium/login.js` was explicit about the redirect, although not the 302. Am I expecting too much?

**Comment by Jaardy** [comment]
No, I don't think so. I just wanted to check.  I'd say it's more than fair to expect that they write to the tests.
